########
### API ####
#########

###
POST http://localhost:3000/api/students
Content-Type: application/json

{
    "name": "Emilio Alvarez", 
    "nickname": "emilio123", 
    "email": "emil.123@emil.com", 
    "phone": "+34 2345234", 
    "password": "12345", 
    "age": 15, 
    "status": 2, 
    "role_id": 1, 
    "location_id": 1,
    "photo": "url"

}

###
GET http://localhost:3000/api/students/

###
GET http://localhost:3000/api/students/5

###
PUT http://localhost:3000/api/students/5
Content-Type: application/json

{
    
    "name": "Emilio Alvarez", 
    "nickname": "emilio123", 
    "email": "em.12356@emil.com", 
    "phone": "+34 232345234", 
    "password": "12345", 
    "age": 15, 
    "status": 2, 
    "role_id": 1, 
    "location_id": 1,
    "photo": "url"

}

###
DELETE http://localhost:3000/api/students/2





######## POSTS

###
POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "titulo": "Libro",
    "description": "romane",
    "fecha_de_creacion": "2023.02.20",
    "categoria": "aburrido",
    "autores_idautores": "5"

}

###
GET http://localhost:3000/api/posts/

###
GET http://localhost:3000/api/posts/5

###
PUT http://localhost:3000/api/posts/1
Content-Type: application/json


    {
    "titulo": "Libro",
    "description": "crimi",
    "fecha_de_creacion": "01.01.2023",
    "categoria": "aburrido",
    "autores_idautores": "1"

}



###Register
POST: http://localhost:3000/api/users/register
{
    "name": "rubenes Alvarez", 
    "nickname": "rub123", 
    "email": "rube@gmail.com", 
    "phone": "6423634548", 
    "password": "12345", 
    "date_of_birth": "1993-02-15", 
    "status": 2, 
    "role_id": 1, 
    "photo": "url"
}
### DEVUELVE
{
  "success": "Login Correcto",
  "token": {
    "user_id": 6,
    "user_name": "ruben Alvarez",
    "user_email": "rub@gmail.com",
    "user_birthday": "1993-02-15",
    "user_role": 1,
    "user_status": 2,
    "user_location": 2,
    "user_creation_date": "2023-11-25 12:50:55",
    "user_update_date": "2023-11-25 12:50:55",
    "exp": 1701346284
  }
}


###
DELETE http://localhost:3000/api/posts/6


###
GET http://localhost:3000/api/posts/autor/1